### PR TITLE
Added Socialsharing feature on Homepage

### LINKED ISSUE #165: Redundant code in Homepage.js
- Social share buttons are imported but are not used.
- Social share icons are imported but are not used.
- handleShareModal func is of no use.

### PR DESCRIPTION
**Pull request by vpn1997**
- Fixes #165 as discussed in #166 .

- Now users can share their demos from their Homepage.

@AvaisP please have a look

### CODE REVIEW

**Comment by vpn1997** [comment]
@AvaisP @uttu357 hey yarn install is failing in Travis build . Please have a look.

**Comment by uttu357** [comment]
@vpn1997 Can you remove the linting changes from this PR as it is difficult to review the code changes along with the linting changes?

**Comment by vpn1997** [comment]
@uttu357 Sure :smile:

**Comment by vpn1997** [comment]
@uttu357 @AvaisP Done

**Comment by vpn1997** [comment]
@uttu357 i have made a separate component and  imported it in homePage.js as well as usershareprofile.js

**Comment by uttu357** [comment]
LGTM! Merging! :+1:

**Pull request merged**
