### PR TITLE
Validate create demo form

### LINKED ISSUE #250: Form validation functionality
- Demo_register page does not have any form validation enabled.
- User should get to know which details are necessary to fill and there should be restriction on the length of input such as `Demo name` and `Demo description`.
- Free Feel to add some more points.

### PR DESCRIPTION
**Pull request by itaisteinherz**
## Description

This adds validation to the task creation form. If the user hasn't met all of the required conditions, Origami won't proceed to the instructions page. Instead, the user will be asked to fix the issues in order to meet the requirements.
Fixes #250.

## Reviewers
@RishabhJain2018 @techytushar

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Other

## Checklist:

- [x] My code follows the code style (modified PEP8) of this project.
- [ ] I have updated the documentation accordingly.
- [x] The code has been tested locally.
Note: Running `yarn run lint:fix` took a lot of time so I stopped the command while it was running, and `python manage.py test` failed. I'll investigate into the issue later.

### CODE REVIEW

**Comment by itaisteinherz** [comment]
Note that I can revert c39346b363b35571fd510dfade6e8d2d17f8af08 and open a separate PR to fix linting.

**Comment by vpn1997** [comment]
@itaisteinherz  Hey please create a seprate Pr for linting otherwise it will be very hard to review this :smile: .

**Comment by itaisteinherz** [comment]
@vpn1997 Sure 👌🏻

**Comment by itaisteinherz** [comment]
@vpn1997 Moved c39346b363b35571fd510dfade6e8d2d17f8af08 to #256.

**Comment by vpn1997** [comment]
@itaisteinherz hey i checked your PR . Everything looks cool but just a minor change.While checking the system config , please specify the specific system config(OS,python ,cuda) that the user needs to select.As of now it is showing all the config(even the ones that are selected).

**Comment by itaisteinherz** [comment]
@vpn1997 Done

**Comment by itaisteinherz** [comment]
@techytushar Done in b34674a503ff75e5628509ec4c815f8eb82f3a0a.

**Comment by vpn1997** [comment]
@itaisteinherz hey if  I am selecting os and cuda  but nor python,it is still showing `Please select cuda version`.Also the errors should be in serial order like error related to name/description should come first,then task,then sys config and lastly optional config. Please fix the bug and make these changes. :smile:

**Comment by itaisteinherz** [comment]
@vpn1997 Done in 0c3dcd297469edb452d9bbef9fbdf5035f525a63.
// cc @techytushar

**Comment by vpn1997** [comment]
@itaisteinherz LGTM :+1: .great work !

**Comment by itaisteinherz** [comment]
@vpn1997 @techytushar I'd love to get an explanation on how you maintain the repo. I noticed that the default branch is `master` and the `latest` branch seems to be used for development. What is the `develop` branch used for?

**Comment by vpn1997** [comment]
@itaisteinherz  hey so `master` is the default branch , the `latest` branch has some features(zip file upload and download) whose test are not written(its also one of the gci tasks, feel free to work on that).So we will merge it with master after the tests are done.Regarding `develop` branch , it was regarding CI/CD pipeline on which @fristonio was working on during GSoC .

**Pull request merged**
