### PR TITLE
bash start script

### PR DESCRIPTION
**Pull request by trexdinosaur**
As discussed over gitter!

Requirements:
To use it you must be CD'd into the project folder and the VENV at the default location. You also will need to have tmux installed.

### CODE REVIEW

**Comment by AvaisP** [comment]
Update the Readme with instructions on how to use this

**Comment by PalashTanejaPro** [comment]
@AvaisP @trexdinosaur Wouldn't it be better if the user is given an option to change specifics like his virtualenv name. I for one did not have my virtualenv named as venv.

**Comment by trexdinosaur** [comment]
I agree, I will make the changes soon @PalashTanejaPro!

**Comment by AvaisP** [comment]
@PalashTanejaPro The README specifies that venv is the name of your virtual env. If that isn't clear enough, we could change it to <venv>

**Comment by PalashTanejaPro** [comment]
@AvaisP Yes, the README mentions that, but I like to keep names related to the task. So, I used ori as my virtualenv name. But hey, if the majority of users are using venv then I can definitely change the script according to my needs.

**Comment by PalashTanejaPro** [comment]
@AvaisP @trexdinosaur I made the required changes, and I even eliminated the need for tmux. 
You can also see the errors when you run my script.
Should I make a PR for it?


`#!/bin/bash
sudo service postgresql start
sudo docker run -d -p 6379:6379 --name origami-redis redis:alpine
sudo docker start origami-redis
source ori/bin/activate && source origami.env && python manage.py runserver --n$
source ori/bin/activate && source origami.env && python manage.py runworker &
source ori/bin/activate && source origami.env && node server.js &
`

**Comment by trexdinosaur** [comment]
@PalashTanejaPro 

That's exactly the original version of the script I proposed in chat when we first started this discussion. :)

The reason we chose to use tmux, is to get the separation between the moving parts so debugging is way easier. I can change up the script so that it still outputs errors on the main thread.
@vpn1997 mentioned that when he's programming, it was way easier for him to be able to see the errors in separate terminals. 

Also, I do agree that a lot of people will have their venv named something else, so I'm going to add it in as an arg.

**Comment by PalashTanejaPro** [comment]
@trexdinosaur 
Yeah, your version uses the standard commands for starting the scripts, calling it 'exactly the same' is quite misleading. 
https://gist.github.com/trexdinosaur/f98713b974aceb3e38b1065177bec4a3
```
sudo docker run -d -p 6379:6379 --name origami-redis redis:alpine
source ~/venv/bin/activate && source origami.env && python manage.py runserver --noworker &
source ~/venv/bin/activate && source origami.env && python manage.py runworker &
node server.js
```

Against tmux an argument can be made that seeing all errors in one window is convenient and attaching tmux sessions can be quite the pain. 

You also don't see what's going on instantly. I experienced this myself, I started your script and my postgresql was not started so I had to attach sessions to even know what's going on. 

Since tmux is not a part of the standard installation in many distros, we are only adding another dependency.

**Comment by trexdinosaur** [comment]
@PalashTanejaPro I think piping errors from tmux would be a good compromise. 

I tried to find some info about it, but I was unable to locate much.

**Comment by PalashTanejaPro** [comment]
@trexdinosaur Works fine!

**Comment by AvaisP** [comment]
@trexdinosaur Please add this to the README as well

**Comment by AvaisP** [comment]
@PalashTanejaPro Are you still working on this?

**Comment by uttu357** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
