### PR TITLE
Improved installation documentation

### PR DESCRIPTION
**Pull request by Mike-Do**
Everything from adding steps to installing and using Postgresql to disabling Hyper-V on Windows was addressed. Be sure to check out all of the new steps that were added!

## Reviewers

GCI Mentors: @RishabhJain2018 @erikatan
Thank you for taking the time to review my work!

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Other

### CODE REVIEW

**Comment by vpn1997** [comment]
@Mike-Do looks great.But can we have a separate link/readme for the windows part because it looks too lengthy.

**Comment by techytushar** [comment]
Hey, you can use dropdowns to make things more clean and organized.

**Comment by Mike-Do** [comment]
@erikaaatan @vpn1997 @techytushar @RishabhJain2018 I've condensed the README using drop-downs. I can always make a separate link/README (primarily for the Windows section), but I personally feel it is more precise to have one README. Thank you.

**Comment by vpn1997** [comment]
@Mike-Do hey are you still working on this? If so then please update the PR with the requested changes. :slightly_smiling_face: .

**Comment by Mike-Do** [comment]
@vpn1997 Yes, I've finished. Is the commit from Nov. 11 showing up on your side? 🤔

**Comment by vpn1997** [comment]
@Mike-Do  hey i added some comments regarding step 7 and step 8 . I think you missed those comments :slightly_smiling_face: .

**Comment by Mike-Do** [comment]
Hello @vpn1997 apologies for the late response. I'm having trouble finding your comments, where are they? Thank you.

**Comment by Mike-Do** [comment]
@vpn1997 Thank you! I've removed the step.

**Comment by vpn1997** [comment]
@Mike-Do hey please sort the travis build issue so that i can merge this.

**Comment by Mike-Do** [comment]
The PR is ready to be merged once one approving review has been completed!

**Comment by vpn1997** [comment]
Great Work  @Mike-Do .

**Comment by Mike-Do** [comment]
@vpn1997 Thank you, and thank you for reviewing my work.

**Pull request merged**
