### PR TITLE
Create demo (Drag and Drop)

### LINKED ISSUE #78: Change create demo UI
Update the demo creation UI to allow users to create demos using drag and drop

### PR DESCRIPTION
**Pull request by vpn1997**
-  Fixes #78 . Now user can create demo using drag and drop feature. :smile: 
   Demo (https://drive.google.com/file/d/14IwNJA75zmjQAvspgxbTENbcyTmYFj4g/view)

@AvaisP @uttu357   please have a look .

### CODE REVIEW

**Comment by vpn1997** [comment]
Please create new demos while testing , it does not work on old demos. :smile:

**Comment by AvaisP** [comment]
@vpn1997 Is it possible to split this into multiple PRs?

**Comment by vpn1997** [comment]
@AvaisP Hey it is regarding single issue only . I dont think we need to split it into more Prs.

**Comment by AvaisP** [comment]
@vpn1997 Yes I know its regarding a single issue, but I do not want to have just one commit for the entire drag and drop feature. Let me know if you can split it into 2-3 smaller PRs. Else I'll review this tomorrow

**Comment by vpn1997** [comment]
hey @AvaisP you can check the functionalities but there are some UI glitches yet to be sorted out . I am currently working on those now . And regarding splitting , sorry but i cant find a way to split this Pr without disturbing the functionality.

**Comment by vpn1997** [comment]
@AvaisP hey you can start reviewing this pr . There are some changes related to base_component_id (which is not required in current drag n drop demo creation model) but ill do those changes in a different pr.

**Comment by vpn1997** [comment]
@AvaisP Hey so can we them option between horizontal and vertical stacking? Because sorting when both horizontal and vertical components are present can a bit tricky . :smile:

**Comment by vpn1997** [comment]
@I'll try to add this feature as soon as possible :smile:  . 
Do we want something similar to this ?
export 5

**Comment by AvaisP** [comment]
Something similar :) (and prettier :P)

**Comment by vpn1997** [comment]
Hey this modification may not be that trivial as it seems :smile: . Basically we have to start all over again since libraries i am using are not giving the desired output that we are looking for.
Also there is a problem of storing demo props. Now we will have to store the position of the individual  component in the database.I can work on this but this can be time consuming. 
An alternative could be that we give user an option between horizontal or vertical stacking but not both of them simultaneously.
Whats you say on this ?
@AvaisP

**Comment by AvaisP** [comment]
@vpn1997 I like the grid layout :smile:. I am not too sure about the alternative solution. @deshraj What are your thoughts on this?

**Comment by deshraj** [comment]
This looks great. Let's go with this

**Comment by AvaisP** [comment]
@vpn1997 What is the current status of this PR?

**Comment by vpn1997** [comment]
@AvaisP  i have not made any changes after @deshraj agreed to go on with this pr.I'll have to resolve the conflicts tho.

**Comment by AvaisP** [comment]
@vpn1997, @deshraj meant go ahead with https://github.com/STRML/react-grid-layout

**Comment by deshraj** [comment]
Sorry for the confusion guys.

**Comment by vpn1997** [comment]
@AvaisP @deshraj well so ill need some time to incorporate those changes .Most probably after submitting my proposal , if thats okay :smile:  .

**Comment by AvaisP** [comment]
Yeah that's okay @vpn1997

**Comment by vpn1997** [comment]
Made some progress @AvaisP :smile: 
(https://drive.google.com/file/d/1baNAHvA2w7wiV5PRYFt2iNU2zYvoIxio/view)

**Comment by AvaisP** [comment]
Great work!

**Comment by vpn1997** [comment]
- Hey  @AvaisP  checkout this (https://drive.google.com/file/d/1ynbJLPBuhyN8tIIdHWPrpf38Qi1eWmHu/view)
 
A lot of finishing work still needs to be done.Will commit these changes in next few days  . :smile:

**Comment by vpn1997** [comment]
@AvaisP hey can you check this .I have done  most of the changes. Need to pass through prettier though.

**Comment by vpn1997** [comment]
@AvaisP Hey can you please check this PR. I'll pass this through prettier if its mergeable .I am currently working on making this responsive :smile:  .

**Comment by vpn1997** [comment]
@AvaisP Please have a look. Suggest some changes if needed. :smile:

**Comment by vpn1997** [comment]
@AvaisP @uttu357 hey i think we need to add a scroll bar for both input and output components in the final demo page since their alignment can be quite messy .Whats say ?
Something like this (https://drive.google.com/file/d/1l9bnMG7B-UBLndBmCNuKSs_l46c9eS7b/view)

**Comment by vpn1997** [comment]
@AvaisP @uttu357 hey can you check the functionality and give me some feedback . :smile: . If its good then i will clean this PR for review .

**Pull request closed without merging**
