### PR TITLE
GCI Task: Made existing codebase compatible with python3

### PR DESCRIPTION
**Pull request by c0derlint**
GCI Task: Made existing codebase compatible with python3

## Description
Changed a few python2-only imports to python 3 compatible ones, including md5 and smart_unicode.

### CODE REVIEW

**Comment by c0derlint** [comment]
@RishabhJain2018 @techytushar After asking me to fix the Travis build, I've been trying to figure out what is wrong, and have fixed multiple errors. However, It is still failing, and I am not able to identify the issue. Please help me out here.

**Comment by vpn1997** [comment]
@c0derlint Hey the unit tests are failing . Try running `python manage.py test` on your local sys.

**Comment by vpn1997** [comment]
@c0derlint  please resolve the conflicts.

**Comment by vpn1997** [comment]
LGTM :+1:

**Pull request merged**
