### PR TITLE
pref(react-router): Upgrade react router to version 4 Fixes #97

### LINKED ISSUE #97: Updating react-router to v4 leads to breaking changes
Npm package react-router-dom needs to be added, for react-router to be upgraded to v4. Code needs to be rewritten as well as react-router v4 is a complete rewrite from react-router v3. Recommended to look through https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md

One error message is: 
> Warning: Failed prop type: The prop `history` is marked as required in `Router`, but its value is `undefined`. in Router

Node version: v8.9.1

npm version: 5.5.1

Operating system: ubuntu 16.04

### PR DESCRIPTION
**Pull request by fristonio**
- bump react-router to version 4
- Fixes #97
- Add use of history and match props using withRouter from react-router.
- Changed application routes structure.

### CODE REVIEW

**Comment by fristonio** [comment]
@AvaisP can you have a look at the PR. I might have missed something :sweat_smile:

**Comment by uttu357** [comment]
@fristonio This file has not been edited to match the current version of react-router. https://github.com/Cloud-CV/Origami/blob/master/Origami/src/components/deployment/UsePrebuiltProject/nghDemoFrame.js

**Comment by fristonio** [comment]
Sorry, I missed that. I have updated the file and also fixed another one in `App.js` Can you again have a look at the Pull Request? @uttu357

**Comment by AvaisP** [comment]
@uttu357 Is this fixed?

**Comment by uttu357** [comment]
@AvaisP Yeah! LGTM! Merging.. :+1:

**Pull request merged**
