### PR TITLE
Improve installation documentation

### PR DESCRIPTION
**Pull request by gautamjajoo**
Improve installation documentation on the ReadME.

1. Deleted Production setup as docker is not working currently. We can add once the functionality is implemented.
2. License file is absent in the project. Please add so that the ReadME is updated with the link. We can add this [file](https://github.com/Cloud-CV/Fabrik/blob/master/LICENSE) .
3. Some additions and deletions with respect to proper documentation.

For viewing the [Markdown file](https://github.com/gautamjajoo/Origami/tree/update_readme) 
@RishabhJain2018 @vpn1997 @erikaaatan

### CODE REVIEW

**Comment by erikaaatan** [comment]
The edits here are not bad, but I think it'd be helpful if there were more step-by-step instructions for beginners and solutions to common errors added here, rather than fixing the formatting. Any thoughts @RishabhJain2018 @vpn1997 ?

**Comment by vpn1997** [comment]
@gautamjajoo agree with @erikaaatan .This Pr looks good but I think we should focus more on addressing the common problem faced during installation.Like installation on windows, Regarding `origami.env` etc.

**Comment by gautamjajoo** [comment]
@vpn1997 Ok. As the latest PR adds the installation instructions for Windows. I can add a file containing Common Errors during nstallation and add the errors and the solutions for it. Is that ok?

**Comment by vpn1997** [comment]
@gautamjajoo Sure :+1: .

**Comment by gautamjajoo** [comment]
Closing this PR and opening a new one .

**Pull request closed without merging**
