### PR TITLE
Show 404 error on invalid requests

### PR DESCRIPTION
**Pull request by itaisteinherz**
## Description

Beforehand, there was no error shown when the user navigated to an invalid URL. This makes the frontend show the default 404 error on invalid requests.

## Reviewers

@techytushar @RishabhJain2018

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

## Screenshots (if appropriate):

Before:

Before

After:

after

## Checklist:

- [x] My code follows the code style (modified PEP8) of this project.
- [ ] I have updated the documentation accordingly.
- [x] The code has been tested locally.

### CODE REVIEW

**Comment by vpn1997** [comment]
@itaisteinherz please resolve the conflicts.

**Comment by itaisteinherz** [comment]
@vpn1997 Done.

**Comment by vpn1997** [comment]
@itaisteinherz hey can you make `404 error` a bit larger.May be a bit more aesthetically better designed 404 page ?

**Comment by itaisteinherz** [comment]
@vpn1997 I'll try to come up with a more elegant 404 page.

**Comment by itaisteinherz** [comment]
@vpn1997 @techytushar I think the new and improved 404 page looks pretty good:

404 Page

Let me know if you'd like me to make any other improvements.

**Comment by vpn1997** [comment]
@itaisteinherz  hey this looks great ! Fix the travis-ci  then ill merge this.

**Comment by itaisteinherz** [comment]
@vpn1997 Ready to merge :)

**Pull request merged**
