### PR TITLE
Modified Register Page

### PR DESCRIPTION
**Pull request by vpn1997**
* Modified Register Page UI.

### CODE REVIEW

**Comment by vpn1997** [comment]
Video - https://drive.google.com/file/d/1ILQMnRxcaaYESXmEvWbp_gJmvs2gz0Vf/view

**Comment by AvaisP** [comment]
@vpn1997 Please resolve the conflicts

**Comment by vpn1997** [comment]
@AvaisP Done.

**Comment by AvaisP** [comment]
@vpn1997 Fix the conflicts

**Comment by vpn1997** [comment]
@AvaisP done.

**Comment by vpn1997** [comment]
@AvaisP

**Pull request merged**
