### PR TITLE
Update npm dependencies in package.json

### PR DESCRIPTION
**Pull request by owenl131**

### CODE REVIEW

**Comment by AvaisP** [comment]
We don't have tests for the frontend yet. Please run the server locally and check if everything works  :)

**Comment by owenl131** [comment]
I have run all the steps on the README from Development setup instructions to Start the server

**Comment by owenl131** [comment]
image

**Comment by owenl131** [comment]
Alright, I have looked through https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes and cross-checked the source code and I have not found anything that might break.

**Comment by AvaisP** [comment]
Oh great!

**Comment by AvaisP** [comment]
Hey this has broken the npm dependencies. Please check the gitter channel. The task is to update the dependencies and report bugs!

**Comment by owenl131** [comment]
Oh dear, I will look into it

**Comment by owenl131** [comment]
Package react-router-dom needs to be added, for react-router to be upgraded to v4. Code needs to be modified as well.
https://stackoverflow.com/questions/43008036/the-prop-history-is-marked-as-required-in-router-but-its-value-is-undefine

**Comment by owenl131** [comment]
React.PropTypes is deprecated, need to switch to PropTypes in the prop-types package. The prop-types package is already installed, and most files are using it, except DropboxChooser.js

**Comment by owenl131** [comment]
@AvaisP I made a pull request rolling back the libraries which are affecting the build.

**Comment by owenl131** [comment]
I will do a bit more testing before sending in the pull request again

**Pull request merged**
