### PR TITLE
GCI Task: Always updated input previews

### PR DESCRIPTION
**Pull request by PalashTanejaPro**
image

  # Update
image

Removed Send button <b>only</b> from previews.

### CODE REVIEW

**Comment by AvaisP** [comment]
Why is the send button displayed?

**Comment by PalashTanejaPro** [comment]
@AvaisP it was there in the preview tab previously as well, I can remove it if you'd like.

**Comment by PalashTanejaPro** [comment]
image
Removed Send button <b>only</b> from previews.

**Comment by AvaisP** [comment]
@PalashTanejaPro  keep a button which when pressed displays the preview of the input components together (not side by side)

**Comment by PalashTanejaPro** [comment]
@AvaisP just checking if I correctly understood? do you want only one preview button that displays them together and should the previews be displayed without the pressing of that button?

**Comment by AvaisP** [comment]
One preview button, yes. Previews should only be displayed when the button is pressed

**Comment by AvaisP** [comment]
Yes this is great!
Just use a better color for the preview button and pass your js files through prettier and you're good to go! :D

**Comment by PalashTanejaPro** [comment]
Ran prettier and changed the button color to blue.
screen shot 2018-01-15 at 12 42 50 am

**Comment by uttu357** [comment]
Closing this as it is being made redundant by #133.

**Pull request closed without merging**
