### PR TITLE
Fix linting

### PR DESCRIPTION
**Pull request by itaisteinherz**
## Description
This fixes all of the automatically-fixable linting errors in the Node.js code.
Based on c39346b363b35571fd510dfade6e8d2d17f8af08 from #255.

## Reviewers
@vpn1997

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Other

## Checklist:
- [x] My code follows the code style (modified PEP8) of this project.
- [ ] I have updated the documentation accordingly.
- [x] The code has been tested locally.

### CODE REVIEW

**Comment by vpn1997** [comment]
@itaisteinherz  hey is this still relevant ?

**Comment by itaisteinherz** [comment]
@vpn1997 Yeah, I'll fix the merge conflict and run linting again.

**Comment by itaisteinherz** [comment]
@vpn1997 Would you like me to add [`autopep8`](https://github.com/hhatto/autopep8), which automatically lints and fixes linting errors according to the project's PEP8 config?

**Comment by vpn1997** [comment]
@itaisteinherz  yeah that will be great !

**Pull request merged**
