### PR TITLE
Fix dependencies causing breaks

### PR DESCRIPTION
**Pull request by owenl131**
Rollback the dependency updates for the following npm dependencies:
- react
- react-dom
- react-router
- react-tap-event-plugin

### CODE REVIEW

**Comment by owenl131** [comment]
Gives the following warnings during webpack compilation:
- warning " > antd@3.0.1" has incorrect peer dependency "react@>=16.0.0".
- warning " > antd@3.0.1" has incorrect peer dependency "react-dom@>=16.0.0".
- warning "antd > rc-editor-mention@1.1.1" has unmet peer dependency "immutable@~3.7.4".
- warning " > babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".

**Comment by owenl131** [comment]
The webpack compilation now gives:
- warning "antd > rc-editor-mention@1.1.1" has unmet peer dependency "immutable@~3.7.4".
- warning "antd > react-slick@0.15.4" has incorrect peer dependency "react@^0.14.0 || ^15.0.1".
- warning "antd > react-slick@0.15.4" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.1".
- warning " > babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
- warning " > react-addons-test-utils@15.6.2" has incorrect peer dependency "react-dom@^15.4.2".

**Comment by owenl131** [comment]
Commit "Change React.PropTypes to PropTypes" is to address #96

**Comment by owenl131** [comment]
In the Home page: 
Warnings: Unsupported style property box-shadow. Did you mean boxShadow?
Warnings: Unsupported style property font-size. Did you mean fontSize?
    in div (created by Basic)
    in Basic (created by Adapter)
    in Adapter (created by HomePage)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by HomePage)
    in HomePage (created by Connect(HomePage))
    in Connect(HomePage) (created by RouterContext)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in MuiThemeProvider
    in Provider
    in LocaleProvider

**Comment by AvaisP** [comment]
Hey @owenl131 
Is everything working apart from these 2 warnings?

**Comment by owenl131** [comment]
Yes

**Comment by AvaisP** [comment]
Yes I've tested most of it too. It works. Good Job!

P.S: We should really start using Selenium to test the UI :P

**Comment by owenl131** [comment]
Yup :D

**Pull request merged**
