### PR TITLE
Improve Origami pull request template.

### PR DESCRIPTION
**Pull request by fristonio**
* The Pull Request improves the PULL_REQUEST_TEMPLATE for Origami.

### CODE REVIEW

**Comment by vpn1997** [comment]
In the checklist we can add .Thoughts?
 - [ ]  Have you followed the guidelines in our Contributing document?
 - [ ]  Have you checked to ensure there aren't other open Pull Requests for the same update/change?
 - [ ]  Have you written new tests for your core changes, as applicable?

**Comment by fristonio** [comment]
Again bloating won't be a good idea, including all of these won't be necessary. Though I liked the mentioned points. So I propose that we should merge the checklist provided by you. How about this
* I have followed the guidelines in CloudCV Contributing document.
* I have written new tests for core changes, as applicable.
* I have updated the documentation accordingly.
Or tell me if we should add something else.

**Comment by vpn1997** [comment]
Seems good tho we can add a point regarding the duplicacy  of the PR.

**Comment by fristonio** [comment]
It would be better to have this in html comments as in here https://github.com/Cloud-CV/Origami/pull/222/files#diff-195a635ad245ded9076330e31134bd80R2

**Pull request merged**
